name: My First Github Action
on:
  push:
   branches: [main]
jobs:
  hello:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up python
        uses:  actions/setup-python@v5  
        with:
          python-version: 3.12
      - name: Check python Version    
        run: python --version
      - name: Show Environment
        env:
         ENVIRONMENT: production
        run: echo "$ENVIRONMENT"
      - name:  Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        run : python test.py
      - name: Generate Test Reports
        run: echo "Test Passed Successfully" > test-report.txt  
      - name: Upload Test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-report.txt


      
      - name: Inspect Runner
        if: always()
        run: |
          pwd
          ls
     

      - name: Say hello
        run: echo "Hello from Github Actions"
 report: 
   needs: hello
   runs-on: ubuntu-latest
   steps:
     - name: Download Test Reports
       uses: actions/download-artifact@v5
       with:
         name: test-report
         path: test-report.txt
     - name: Inspect Download Artifacts
       run: |
        ls  
        pwd  