name: My First Github Action
on:
  push:
   branches: [main]
jobs:
  hello:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up python
        uses:  actions/setup-python@v6
        with:
          python-version: 3.12
      - name: Check python Version    
        run: python --version
      - name: Cache pip
        uses: actions/cache@v5
        with:
           path: ~/.cache/pip
           key: ubuntu-latest-python-3.12-${{ hashFiles('requirements.txt') }}  
           restore-keys: ubuntu-latest-python-3.12-
      - name: Show Environment
        env:
         ENVIRONMENT: production
        run: echo "$ENVIRONMENT"
      - name:  Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        run : python test.py
      - name: Test Successfull
        if: success()
        run: echo "All Previous steps succeeded"  
      - name: Generate Test Reports
        run: echo "Test Passed Successfully" > test-report.txt  
      - name: Upload Test reports
        uses: actions/upload-artifact@v6
        with:
          name: test-report
          path: test-report.txt


      
      - name: Inspect Runner
        if: always()
        run: |
          pwd
          ls
     

      - name: Say hello
        run: echo "Hello from Github Actions- Cache Test"
      - name: Deciding Contexts
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "Running on the main branch" 
      - name: Checking Event 
        if: ${{ github.event_name == 'push' }} 
        run: echo "Push event Trigerred the workflow" 
      - name: Checking events and main
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        run: echo "Push on main branch"
      - name: Checking CI events
        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}  
        run: echo "CI Event Detected"
      - name: Checking Non Push Event
        if: ${{ github.event_name != 'push' && github.event_name == 'pull_request' }}
        run: echo "Non-push Event Detected"
  report: 
    needs: hello
    runs-on: ubuntu-latest
    steps:
       - name: Download Test Reports
         uses: actions/download-artifact@v7
         with:
           name: test-report
           path: test-report.txt
       - name: Inspect Download Artifacts
         run: |
          ls  
          pwd  
      